import React, { useState } from 'react';
import styles from './CourseForm.module.css'; // Assuming we will create a CSS file for styles
import stylesButton1 from '../../../shared/components/Button1.module.css'; // Importing Button1
import LoadingSpinner from '../../../shared/components/LoadingSpinner'; // Importing LoadingSpinner
import { useTranslation } from 'react-i18next'; // Importing useTranslation

// Constants for resource types and evaluation methods
const RESOURCE_TYPES = [
    { value: 'scorm', label: 'HTML5 (diapositivas interactivas)' },
    { value: 'video', label: 'Video' },
    { value: 'audio', label: 'Audio' },
    { value: 'text', label: 'Archivos de texto (Word, Excel, txt y PDF)' },
    { value: 'ppt', label: 'PPT' },
    { value: 'url', label: 'URL' },
];

const EVALUATION_METHODS = [
    { value: 'diagnostic', label: 'Evaluación de diagnóstico' },
    { value: 'module', label: 'Evaluaciones por módulo' },
    { value: 'final', label: 'Evaluación final' },
];

const CourseForm = ({ onSubmit }) => {
    const { t } = useTranslation(); // Using the translation hook
    const [courseName, setCourseName] = useState('');
    const [contentSource, setContentSource] = useState('auto-generated');
    const [estimatedTime, setEstimatedTime] = useState('');
    const [participantProfile, setParticipantProfile] = useState('');
    const [courseObjective, setCourseObjective] = useState('');
    const [resourceTypes, setResourceTypes] = useState([]);
    const [addActivities, setAddActivities] = useState(false);
    const [evaluationMethods, setEvaluationMethods] = useState([]);
    const [feedback, setFeedback] = useState(false);
    const [toneStyle, setToneStyle] = useState('');
    const [additionalContext, setAdditionalContext] = useState('');
    const [loading, setLoading] = useState(false); // Loading state

    const handleSubmit = async (e) => {
        e.preventDefault();
        window.scrollTo(0, 0); // Scroll to the top of the page
        setLoading(true); // Set loading to true
        
        // Convert list-type fields to comma-separated strings with labels
        const formattedResourceTypes = resourceTypes.map(type => 
            RESOURCE_TYPES.find(option => option.value === type)?.label
        ).join(', ');

        const formattedEvaluationMethods = evaluationMethods.map(method => 
            EVALUATION_METHODS.find(option => option.value === method)?.label
        ).join(', ');

        await onSubmit({
            courseName,
            contentSource,
            estimatedTime,
            participantProfile,
            courseObjective,
            resourceTypes: formattedResourceTypes, // Use formatted string
            addActivities,
            evaluationMethods: formattedEvaluationMethods, // Use formatted string
            feedback,
            toneStyle,
            additionalContext,
        });

        setLoading(false); // Set loading to false after submission
    };

    return (
        <>
            {loading ? <LoadingSpinner /> : (
                <form onSubmit={handleSubmit} className={styles.form}>
                    <h1 className={styles.formTitle}>{t('createCourse')}</h1>
                    <div className={styles.fieldContainer}>
                        <label>{t('courseNameLabel')} <span style={{ color: 'red' }}>*</span></label>
                        <input
                            type="text"
                            className={styles.inputField} // Applying the inputField class
                            value={courseName}
                            onChange={(e) => setCourseName(e.target.value)}
                            placeholder={t('courseNamePlaceholder')}
                            required
                        />
                    </div>
                    <div className={styles.fieldContainer}>
                        <label>{t('contentSourceLabel')}</label>
                        <select 
                            className={styles.selectField} // Applying the selectField class
                            value={contentSource} 
                            onChange={(e) => setContentSource(e.target.value)}
                        >
                            <option value="auto-generated">{t('autoGenerated')}</option>
                            <option value="specific-source">{t('specificSource')}</option>
                        </select>
                    </div>
                    <div className={styles.fieldContainer}>
                        <label>{t('estimatedTimeLabel')} <span style={{ color: 'red' }}>*</span></label>
                        <input
                            type="number" // Changed to number type
                            className={styles.inputField} // Applying the inputField class
                            value={estimatedTime}
                            onChange={(e) => setEstimatedTime(e.target.value)}
                            placeholder={t('estimatedTimePlaceholder')}
                            required
                        />
                    </div>
                    <div className={styles.fieldContainer}>
                        <label>{t('participantProfileLabel')} <span style={{ color: 'red' }}>*</span></label>
                        <input
                            type="text"
                            className={styles.inputField} // Applying the inputField class
                            value={participantProfile}
                            onChange={(e) => setParticipantProfile(e.target.value)}
                            placeholder={t('participantProfilePlaceholder')}
                            required
                        />
                    </div>
                    <div className={styles.fieldContainer}>
                        <label>{t('courseObjectiveLabel')} <span style={{ color: 'red' }}>*</span></label>
                        <input
                            type="text"
                            className={styles.inputField} // Applying the inputField class
                            value={courseObjective}
                            onChange={(e) => setCourseObjective(e.target.value)}
                            placeholder={t('courseObjectivePlaceholder')}
                            required
                        />
                    </div>
                    <div className={styles.fieldContainer}>
                        <label>{t('resourceTypesLabel')}</label>
                        <select 
                            multiple 
                            className={styles.selectField} // Applying the selectField class
                            value={resourceTypes} 
                            onChange={(e) => setResourceTypes([...e.target.selectedOptions].map(option => option.value))}
                        >
                            {RESOURCE_TYPES.map((type) => (
                                <option key={type.value} value={type.value}>{type.label}</option>
                            ))}
                        </select>
                    </div>
                    <div className={styles.fieldContainer}>
                        <label>{t('addEvaluationLabel')}</label>
                        <input
                            type="checkbox"
                            checked={addActivities}
                            onChange={(e) => setAddActivities(e.target.checked)}
                        />
                    </div>
                    {addActivities && (
                        <>
                            <div className={styles.fieldContainer}>
                                <label>{t('evaluationMethodsLabel')}</label>
                                <select 
                                    multiple 
                                    className={styles.selectField} // Applying the selectField class
                                    value={evaluationMethods} 
                                    onChange={(e) => setEvaluationMethods([...e.target.selectedOptions].map(option => option.value))}
                                >
                                    {EVALUATION_METHODS.map((method) => (
                                        <option key={method.value} value={method.value}>{method.label}</option>
                                    ))}
                                </select>
                            </div>
                            <div className={styles.fieldContainer}>
                                <label>{t('feedbackLabel')}</label>
                                <input
                                    type="checkbox"
                                    checked={feedback}
                                    onChange={(e) => setFeedback(e.target.checked)}
                                />
                            </div>
                        </>
                    )}
                    <div className={styles.fieldContainer}>
                        <label>{t('toneStyleLabel')}</label>
                        <input
                            type="text"
                            className={styles.inputField} // Applying the inputField class
                            value={toneStyle}
                            onChange={(e) => setToneStyle(e.target.value)}
                            placeholder={t('toneStylePlaceholder')}
                        />
                    </div>
                    <div className={styles.fieldContainer}>
                        <label>{t('additionalContextLabel')}</label>
                        <textarea
                            className={styles.textareaField} // Applying the textareaField class
                            value={additionalContext}
                            onChange={(e) => setAdditionalContext(e.target.value)}
                            placeholder={t('additionalContextPlaceholder')}
                        />
                    </div>
                    <button type="submit" className={stylesButton1.button1}>{t('generateCourseButton')}</button>
                </form>
            )}
        </>
    );
};

export default CourseForm;
